### ISSUE TITLE
csv log unsuccessful, this may be due to a missing dependency or windows component

### ISSUE THREAD

**Issue by Samie27** [amitxv/AutoGpuAffinity#7]
how do i fix this i already turn off anti virus and redownload it still doing that error

**Comment by amitxv** [comment]
That error occurs when PresentMon is unable to log frametime data to a CSV file. It works on a stock Windows installation so consider reinstalling.

**Comment by Samie27** [comment]
reinstall what? the presentmon?

**Comment by amitxv** [comment]
Windows. Make sure you are using the latest version.

**Comment by Samie27** [comment]
ahh okay thanks

**Comment by ElayHadad** [comment]
Got the same error, but I have found that "lava-triangle.exe" is the culprit.
I have tested "PresentMon" ability to log DWM into csv file and it worked just fine, but when I try to ran solely "lava-triangle.exe" it logged "VkResult VK_ERROR_INITIALIZATION_FAILED".
To confirm this I tried on two computers, both of them have the same modified version of windows 10. So the problem might be the GPU? Meaning no need to bother reinstalling windows.

**Comment by amitxv** [comment]
I added a D3D9 alternative for this reason. https://github.com/amitxv/AutoGpuAffinity/blob/9b8bcc7ed6941b0616d853f6cc0d44f56df969ce/src/config.ini#L13-L15

**Comment by ElayHadad** [comment]
Splendid! Phew, I started coding an alternative benchmark using OpenGL. Hassle free solution.

Though, I think there might be methods to benchmark, since this workload doesn't reflect real-world performance as it doesn't have any complex rendering scenes that would stress the GPU (and the core it has been affinited to).

Maybe I will work on an alterantive after all when I'll have some free time. There is no need to rewrite a whole benchmark, Can simply utilize Unigine-Heaven in your code instead of replacing the .exe benchmark file.
Anyhow, just an idea. For now I'll use this, thanks a lot!

**Comment by amitxv** [comment]
The goal is not necessarily load the GPU, it's a CPU benchmark at the end of the day.

**Comment by ElayHadad** [comment]
You are right, the goal here is not to detect bottlenecks from manual affinities but to reduce latency, right? Though it might be a nice improvement to the application.
